version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: dota2comfy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dota2comfy_network

volumes:
  postgres_data:
  redis_data:

networks:
  dota2comfy_network:
    driver: bridge